# Generated by Django 2.0.2 on 2018-02-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
